import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// Custom plugin to inline JS and CSS into the HTML, bypassing external dependency bugs
function inlineSingleFile() {
  return {
    name: "inline-single-file",
    enforce: "post",
    generateBundle(_, bundle) {
      const htmlAsset = bundle["index.html"];
      if (!htmlAsset) return;
      let html = htmlAsset.source;

      for (const [key, asset] of Object.entries(bundle)) {
        if (key.endsWith(".css")) {
          const re = new RegExp(`<link[^>]*?href=["'].*?${key}["'][^>]*?>`, "i");
          html = html.replace(re, () => `<style>\n${asset.source}\n</style>`);
          delete bundle[key];
        } else if (key.endsWith(".js")) {
          const re = new RegExp(`<script[^>]*?src=["'].*?${key}["'][^>]*?></script>`, "i");
          html = html.replace(re, () => `<script type="module">\n${asset.code}\n</script>`);
          delete bundle[key];
        }
      }
      
      // Strip out modulepreload links generated by Vite
      html = html.replace(/<link rel="modulepreload"[^>]*?>/gi, "");
      htmlAsset.source = html;
    }
  };
}

export default defineConfig(({ mode }) => {
  const standalone = mode === "standalone";
  
  const plugins = [react()];
  if (standalone) {
    plugins.push(inlineSingleFile());
  }

  return {
    root: process.cwd(),
    base: "./",
    resolve: {
      preserveSymlinks: true,
    },
    plugins,
    build: {
      chunkSizeWarningLimit: 4096,
      assetsInlineLimit: standalone ? 100 * 1024 * 1024 : 4096,
      rollupOptions: standalone ? { output: { manualChunks: undefined } } : {},
      outDir: standalone ? "dist-standalone" : "dist",
    },
  };
});
